# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1
jobs:
  build:
    docker:
      - image: cimg/ruby:3.3.1
    steps:
      - checkout
      - run: ruby --version

  test:
    docker:
      - image: cimg/ruby:3.3.1
    steps: 
      - checkout
      - run: 
          name: Gem Install
          command: bundle install
      - run:
          name: Running Tests 
          command: bundle exec rspec spec

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test